# This is a basic workflow to help you get started with Actions

name: Automated Drupal8 CICD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "service"
  services:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['7.3']
    # Enable the mysql services
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306/tcp
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: drupal8
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10

    steps:
      - name: Check out the code 
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Verify MySQL connection from host
        run: |
          mysqladmin ping
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "SHOW DATABASES"        

      - name: Set up PHP ${{ matrix.php_version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}

      - name: Install Composer dependencies
        run: composer install --dev

  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['7.3']
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306/tcp
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: drupal8
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
    - name: Set up PHP ${{ matrix.php_version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php_version }}

    - name: Check out the code 
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install Composer dependencies
      run: composer install --dev

    - name: Verify MySQL connection from container 
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client
        mysqladmin ping
        #mysql -hmysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS drupal8;"
        #mysql -hmysql -uroot -proot -e "SHOW DATABASES"
        #mysql -hmysql -uroot -proot drupal8 < scripts/database/dumps/drupal8.sql
        #mysql -hmysql -uroot -proot -e "USE drupal8; SHOW TABLES;"
